apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-b
spec:
  selector:
    matchLabels:
      app: app-b
  replicas: 2
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - name: app-b
          image: gcr.io/nnyn-dev/simple-post-server:latest
          args:
            - "--down=service-c:8080"
            - "--pos=35.689634,139.692101"
          env:
            - name: ENABLE_DEBUG
              value: "false"
          resources:
            limits:
              cpu: "500m"
              memory: "1G"
            requests:
              cpu: "100m"
              memory: "200Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
