version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/nnyn-dev/simple-post-server:latest
    ports:
      - 8080:8080
    volumes:
      - /home/nnyn/ghq/github.com/74th/sample-gisapp/test:/app/test
