# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gisapp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gisapp.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12proto/gisapp.proto\x12\x05proto\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"1\n\x12RouteLengthRequest\x12\x1b\n\x05route\x18\x01 \x03(\x0b\x32\x0c.proto.Point\"%\n\x13RouteLengthResponse\x12\x0e\n\x06length\x18\x01 \x01(\x01\x32Q\n\x07GISCalc\x12\x46\n\x0bRouteLength\x12\x19.proto.RouteLengthRequest\x1a\x1a.proto.RouteLengthResponse\"\x00\x62\x06proto3'
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='proto.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='proto.Point.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='proto.Point.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=73,
)


_ROUTELENGTHREQUEST = _descriptor.Descriptor(
  name='RouteLengthRequest',
  full_name='proto.RouteLengthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='route', full_name='proto.RouteLengthRequest.route', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=124,
)


_ROUTELENGTHRESPONSE = _descriptor.Descriptor(
  name='RouteLengthResponse',
  full_name='proto.RouteLengthResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='proto.RouteLengthResponse.length', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=163,
)

_ROUTELENGTHREQUEST.fields_by_name['route'].message_type = _POINT
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['RouteLengthRequest'] = _ROUTELENGTHREQUEST
DESCRIPTOR.message_types_by_name['RouteLengthResponse'] = _ROUTELENGTHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'proto.gisapp_pb2'
  # @@protoc_insertion_point(class_scope:proto.Point)
  })
_sym_db.RegisterMessage(Point)

RouteLengthRequest = _reflection.GeneratedProtocolMessageType('RouteLengthRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUTELENGTHREQUEST,
  '__module__' : 'proto.gisapp_pb2'
  # @@protoc_insertion_point(class_scope:proto.RouteLengthRequest)
  })
_sym_db.RegisterMessage(RouteLengthRequest)

RouteLengthResponse = _reflection.GeneratedProtocolMessageType('RouteLengthResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROUTELENGTHRESPONSE,
  '__module__' : 'proto.gisapp_pb2'
  # @@protoc_insertion_point(class_scope:proto.RouteLengthResponse)
  })
_sym_db.RegisterMessage(RouteLengthResponse)



_GISCALC = _descriptor.ServiceDescriptor(
  name='GISCalc',
  full_name='proto.GISCalc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=246,
  methods=[
  _descriptor.MethodDescriptor(
    name='RouteLength',
    full_name='proto.GISCalc.RouteLength',
    index=0,
    containing_service=None,
    input_type=_ROUTELENGTHREQUEST,
    output_type=_ROUTELENGTHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GISCALC)

DESCRIPTOR.services_by_name['GISCalc'] = _GISCALC

# @@protoc_insertion_point(module_scope)
